#!/usr/bin/python
# -*- coding: utf-8 -*-
# domain wise count for committer and committed domain 
# this will print outs;
#  Number of commiters, number of commits, number of domains
# note: we must user git shortlog -sne
# git shortlog -sn is not goog because of we are not identify same name but different domain
# when -d parameter, we can use 
#  sort -rnk 1 : sort by commiter 
#  sort -rnk 2 : sort by number of commits

domlist = {}  # we will use dictinary

def parsearg():
    # parse arguments: 
    import argparse
    parser = argparse.ArgumentParser(prog='domcount')
    parser.add_argument("-d", help='Detaild, each domain name and its commit count will be shown', action='store_true')
    parser.add_argument("-s", help='Summary will be shown', action='store_true')
    args = parser.parse_args()
    return args


def getdomainname(eaddr):
    # get domain name from email address 
    if eaddr== "<>":
	return eaddr
    ns=eaddr.split('@')  # <name@xx.yy.zz.domain>
    #name = ns[0]
    if len(ns) <= 1:
        return eaddr     # we have no domain name in email
    dn = ns[1].split('.')
    l = len(dn)
    lastwd = dn[l-1]     # last one is domain namae
    fixlwd = lastwd[:len(lastwd)-1]  # cut last char ">"
    domainname = dn[l-2]+'.'+ fixlwd
    #email = name+'@'+dom
    return domainname

def countcommits(domainname, detaillist):
    # return number of commiter, num of commits for a domainname 
    item = domlist[domainname]
    ncommiter = len(item)
    numcommits = 0  # for this domainname
    for i in item:
       numcommits = numcommits + i
    if detaillist :
        # print detailed list
        print ncommiter, " ", numcommits, " ", domainname
    return (ncommiter, numcommits)

def summary(domlist, detaillist, summarylist):
    numdoms = 0
    commiter = 0
    commitcnt = 0
    for domainname in domlist.keys():
        numdoms = numdoms + 1
        (cmter, cmtcnt) = countcommits(domainname, detaillist)
        commiter = commiter + cmter
        commitcnt = commitcnt + cmtcnt
    # print summary and also simple 
    if summarylist :
        print "Total Commiter:", commiter, " Number of Commits:", commitcnt,
        print "Numdomains:", numdoms  
    elif not detaillist :
        print  commiter, "\t", commitcnt, "\t", numdoms,  



if __name__ == "__main__":
  import sys
  # read from stdin, we supporse the result of
  # git sortlog -s -n -e 
  # will come 
  #domlist = {}  # we will use dictinary
  args = parsearg()
  for line in sys.stdin:
      field = line.split()
      l = len(field)
      for i in range(0, l-1):
        if (i == 0):
           commitnum = int(field[i]),
           #if args.d :   # -d specified
           #    print '%5d' % commitnum,
      domainname = getdomainname(field[l-1])
      #if args.d :
      #    print domainname
      if (domainname in domlist):
           last = domlist[domainname]
           domlist[domainname] = last + commitnum
      else:
           domlist[domainname] = commitnum

  #print domlist
  #print "SUMMARY"
  summary(domlist, args.d, args.s)

