#!/usr/bin/python
# -*- coding: utf-8 -*-
# domain wise count for committer and committed domain 
# note: we must user git shortlog -sne
# git shortlog -sn is not goog because of we are not identify same name but different domain


domlist = {}  # we will use dictinary


def getdomainname(eaddr):
    # get domain name from email address 
    if eaddr== "<>":
	return eaddr
    ns=eaddr.split('@')  # <name@xx.yy.zz.domain>
    #name = ns[0]
    if len(ns) <= 1:
        return eaddr     # we have no domain name in email
    dn = ns[1].split('.')
    l = len(dn)
    lastwd = dn[l-1]     # last one is domain namae
    fixlwd = lastwd[:len(lastwd)-1]  # cut last char ">"
    domainname = dn[l-2]+'.'+ fixlwd
    #email = name+'@'+dom
    return domainname

def countcommits(domainname):
    # return number of commiter, num of commits for a domainname 
    item = domlist[domainname]
    ncommiter = len(item)
    numcommits = 0  # for this domainname
    for i in item:
       numcommits = numcommits + i
    return (ncommiter, numcommits)

def summary(domlist):
    numdoms = 0
    commiter = 0
    commitcnt = 0
    for domainname in domlist.keys():
        numdoms = numdoms + 1
        (cmter, cmtcnt) = countcommits(domainname)
        commiter = commiter + cmter
        commitcnt = commitcnt + cmtcnt
    #print
    #print "Total numcommiters: ", commiter, " numcommits: ", commitcnt,
    print  commiter, "\t", commitcnt, "\t", numdoms,  
    #print "Numdomains:", numdoms  



if __name__ == "__main__":
  import sys
  # read from stdin, we supporse the result of
  # git sortlog -s -n -e 
  # will come 
  #domlist = {}  # we will use dictinary
  for line in sys.stdin:
      field = line.split()
      l = len(field)
      for i in range(0, l-1):
        if (i == 0):
           commitnum = int(field[i]),
           #print '%5d' % commitnum,
      domainname = getdomainname(field[l-1])
      #print domain
      if (domainname in domlist):
           last = domlist[domainname]
           domlist[domainname] = last + commitnum
      else:
           domlist[domainname] = commitnum

  #print domlist
  #print "SUMMARY"
  summary(domlist)

